interface AudioItem { bytes: ArrayBuffer; mime: string; sequence: number; sampleRate?: number }
export class PlaybackQueue {
  private queue: AudioItem[] = []; private pending = new Map<number, AudioItem>(); private expected = 1;
  private active: HTMLAudioElement | null = null; private sources = new Set<AudioBufferSourceNode>();
  private context: AudioContext | null = null; private scheduledUntil = 0; private urls = new Set<string>(); private outputDeviceId: string | null = null;
  setOutputDevice(value: string | null) { this.outputDeviceId = value; }
  enqueue(bytes: ArrayBuffer, mime: string, sequence = this.expected, sampleRate?: number): void { if (sequence < this.expected || this.pending.has(sequence)) return; this.pending.set(sequence, { bytes, mime, sequence, sampleRate }); while (this.pending.has(this.expected)) { this.queue.push(this.pending.get(this.expected)!); this.pending.delete(this.expected++); } if (mime === "audio/pcm") this.schedulePcm(); else if (!this.active) void this.nextEncoded(); }
  clear(): void { this.queue = []; this.pending.clear(); this.expected = 1; this.scheduledUntil = 0; this.sources.forEach(source => { try { source.stop(); } catch { /* already stopped */ } }); this.sources.clear(); if (this.active) { this.active.pause(); this.active.src = ""; this.active = null; } this.urls.forEach(url => URL.revokeObjectURL(url)); this.urls.clear(); }
  private schedulePcm() { this.context ||= new AudioContext(); while (this.queue[0]?.mime === "audio/pcm") { const item = this.queue.shift()!; const pcm = new Int16Array(item.bytes); const rate = item.sampleRate ?? 24000; const buffer = this.context.createBuffer(1, pcm.length, rate); const channel = buffer.getChannelData(0); for (let index = 0; index < pcm.length; index++) channel[index] = pcm[index] / 32768; const source = this.context.createBufferSource(); source.buffer = buffer; source.connect(this.context.destination); const start = Math.max(this.context.currentTime + 0.02, this.scheduledUntil); this.scheduledUntil = start + buffer.duration; this.sources.add(source); source.addEventListener("ended", () => this.sources.delete(source), { once: true }); source.start(start); } }
  private async nextEncoded(): Promise<void> { const item = this.queue.shift(); if (!item) { this.active = null; return; } if (item.mime === "audio/pcm") { this.schedulePcm(); return; } const url = URL.createObjectURL(new Blob([item.bytes], { type: item.mime })); this.urls.add(url); const audio = new Audio(url); this.active = audio; const sink = audio as HTMLAudioElement & { setSinkId?: (id: string) => Promise<void> }; if (this.outputDeviceId && sink.setSinkId) await sink.setSinkId(this.outputDeviceId).catch(() => undefined); const finish = () => { URL.revokeObjectURL(url); this.urls.delete(url); if (this.active === audio) this.active = null; void this.nextEncoded(); }; audio.addEventListener("ended", finish, { once: true }); audio.addEventListener("error", finish, { once: true }); await audio.play().catch(finish); }
}
